# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import document_service_pb2 as proto_dot_document__service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/document_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateDocument = channel.unary_unary(
                '/document.DocumentService/CreateDocument',
                request_serializer=proto_dot_document__service__pb2.CreateDocumentRequest.SerializeToString,
                response_deserializer=proto_dot_document__service__pb2.CreateDocumentResponse.FromString,
                _registered_method=True)
        self.JoinDocument = channel.unary_unary(
                '/document.DocumentService/JoinDocument',
                request_serializer=proto_dot_document__service__pb2.JoinDocumentRequest.SerializeToString,
                response_deserializer=proto_dot_document__service__pb2.JoinDocumentResponse.FromString,
                _registered_method=True)
        self.EditDocument = channel.stream_stream(
                '/document.DocumentService/EditDocument',
                request_serializer=proto_dot_document__service__pb2.EditDocumentRequest.SerializeToString,
                response_deserializer=proto_dot_document__service__pb2.EditDocumentResponse.FromString,
                _registered_method=True)
        self.AddEditorStream = channel.unary_unary(
                '/document.DocumentService/AddEditorStream',
                request_serializer=proto_dot_document__service__pb2.AddEditorStreamRequest.SerializeToString,
                response_deserializer=proto_dot_document__service__pb2.AddEditorStreamResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditDocument(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddEditorStream(self, request, context):
        """New RPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateDocument,
                    request_deserializer=proto_dot_document__service__pb2.CreateDocumentRequest.FromString,
                    response_serializer=proto_dot_document__service__pb2.CreateDocumentResponse.SerializeToString,
            ),
            'JoinDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinDocument,
                    request_deserializer=proto_dot_document__service__pb2.JoinDocumentRequest.FromString,
                    response_serializer=proto_dot_document__service__pb2.JoinDocumentResponse.SerializeToString,
            ),
            'EditDocument': grpc.stream_stream_rpc_method_handler(
                    servicer.EditDocument,
                    request_deserializer=proto_dot_document__service__pb2.EditDocumentRequest.FromString,
                    response_serializer=proto_dot_document__service__pb2.EditDocumentResponse.SerializeToString,
            ),
            'AddEditorStream': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEditorStream,
                    request_deserializer=proto_dot_document__service__pb2.AddEditorStreamRequest.FromString,
                    response_serializer=proto_dot_document__service__pb2.AddEditorStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'document.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('document.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/CreateDocument',
            proto_dot_document__service__pb2.CreateDocumentRequest.SerializeToString,
            proto_dot_document__service__pb2.CreateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/JoinDocument',
            proto_dot_document__service__pb2.JoinDocumentRequest.SerializeToString,
            proto_dot_document__service__pb2.JoinDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/document.DocumentService/EditDocument',
            proto_dot_document__service__pb2.EditDocumentRequest.SerializeToString,
            proto_dot_document__service__pb2.EditDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddEditorStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/document.DocumentService/AddEditorStream',
            proto_dot_document__service__pb2.AddEditorStreamRequest.SerializeToString,
            proto_dot_document__service__pb2.AddEditorStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
